name: "build"

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.4pre20210604_8e6ee1b/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v8
      with:
        name: nix-fonts
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -L .\#helvetica-neue .\#helvetica-now-display-otf .\#helvetica-now-display-ttf .\#helvetica-now-micro-otf .\#helvetica-now-micro-ttf .\#helvetica-now-text-otf .\#helvetica-now-text-ttf .\#pragmatapro .\#sanfrancisco-compact .\#sanfrancisco-pro .\#sanfrancisco-mono .\#newyork .\#stimula .\#klavika .\#circularstd-otf .\#circularstd-ttf .\#fk-display .\#fk-grotesk .\#fk-grotesk-semimono .\#fk-grotesk-mono .\#fk-raster-grotesk .\#fk-roman-display .\#fk-roman-text .\#fk-screamer

